# FROM node:18.3.0 As development

# WORKDIR /usr/src/app

# COPY package.json yarn.lock ./

# RUN yarn install

# COPY . .

# RUN yarn build


# FROM node:18.3.0 as production

# ARG NODE_ENV=production

# ENV NODE_ENV=${NODE_ENV}

# WORKDIR /usr/src/app

# COPY package*.json yarn.lock ./

# RUN yarn install

# COPY --from=development /usr/src/app/dist ./dist

# COPY --from=development /usr/src/app/package.json .

# COPY --from=development /usr/src/app/.env .








